![Banner](/6_Assets/Banner_ETL.png)

## ETL Extracción, transformación y carga

⚠️ **Asegúrese de instalar las siguientes bibliotecas antes de ejecutar el código**

- numpy
- pandas
- matplotlib
- seaborn
- geopandas
- geojson
- folium
- re
- sqlalchemy


Puede instalar estas bibliotecas debe abrir una terminal o ventana de línea de comandos y ejecutar el siguiente comando:

*`pip install pandas matplotlib`*

En el doloroso escenario de la realidad argentina, donde anualmente se despiden cerca de 4.000 vidas en siniestros viales, nuestro viaje comienza con una misión fundamental: transformar datos en entendimiento, desvelar los mensajes implícitos y, sobre todo, contribuir a la reducción de tragedias en sus carreteras.

En éste proceso de ETL nos embarcaremos en la tarea de explorar dos archivos en formato Excel, testigos silenciosos de eventos trágicos: **'homicidios.xlsx'** y **'lesiones.xlsx'**. Cada hoja de trabajo, ya sea en homicidios (HECHOS y VICTIMAS) o lesiones (HECHOS y VICTIMAS), guarda consigo relatos que claman por ser desentrañados.

Este notebook no es meramente código; es una odisea de descubrimiento, un esfuerzo meticuloso para revelar los secretos que se ocultan en los datos crudos. Nos sumergiremos en cada fila, exploraremos cada columna, y extraeremos la esencia que yace en cada celda. La transformación de información cruda en conocimiento es la brújula que nos guía hacia la comprensión y, más importante aún, hacia la acción para mitigar las pérdidas humanas en las carreteras de la Ciudad de Buenos Aires.


+ Fuente de datos:

Buenos Aires Data: https://data.buenosaires.gob.ar/dataset/victimas-siniestros-viales

## 1. Importar Librerías

In [23]:
import sqlalchemy
import re
import sketch
import numpy as np 
import pandas as pd 
#import pandas_alive
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
import geojson
import folium
from folium.plugins import HeatMap
from summarytools import dfSummary
from functions import analizar_valores_sd, cargar_datos_desde_excel, data_cleaning


## 2. Cargar de datos

In [16]:
# Acceder al DataFrame por nombre de hoja, Homicidios - Hechos
homicidios_hechos = pd.read_excel("homicidios.xlsx", sheet_name="HECHOS")
homicidios_victimas = pd.read_excel("homicidios.xlsx", sheet_name="VICTIMAS")
comunas= pd.read_excel("comunas.xlsx")


## 3. Explorar y limpiar datos

### 3.1. Dataset: Homicidios - Hechos

In [17]:
# Visualiza las primeras filas del Dataframe
homicidios_hechos



ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
0    2016-0001           1 2016-01-01  2016   1   1  04:00:00   4   
1    2016-0002           1 2016-01-02  2016   1   2  01:15:00   1   
2    2016-0003           1 2016-01-03  2016   1   3  07:00:00   7   
3    2016-0004           1 2016-01-10  2016   1  10  00:00:00   0   
4    2016-0005           1 2016-01-21  2016   1  21  05:20:00   5   
..         ...         ...        ...   ...  ..  ..       ...  ..   
691  2021-0093           1 2021-12-13  2021  12  13  17:10:00  17   
692  2021-0094           1 2021-12-20  2021  12  20  01:10:00   1   
693  2021-0095           1 2021-12-30  2021  12  30  00:43:00   0   
694  2021-0096           1 2021-12-15  2021  12  15  10:30:00  10   
695  2021-0097           1 2021-11-18  2021  11  18  06:10:00   6   

                               LUGAR_DEL_HECHO TIPO_DE_CALLE  ...  Altura  \
0    AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...     NaN   
1            AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...     NaN   
2                           AV ENTRE RIOS 2034       AVENIDA  ...  2034.0   
3        AV LARRAZABAL Y GRAL VILLEGAS CONRADO       AVENIDA  ...     NaN   
4    AV SAN JUAN Y PRESIDENTE LUIS SAENZ PEÑA        AVENIDA  ...     NaN   
..                                         ...           ...  ...     ...   
691                          AV. RIESTRA Y MOM       AVENIDA  ...     NaN   
692                    AU DELLEPIANE Y LACARRA     AUTOPISTA  ...     NaN   
693                        AV. GAONA Y TERRADA       AVENIDA  ...     NaN   
694                         AV. EVA PERON 4071       AVENIDA  ...  4071.0   
695                    PADRE CARLOS MUJICA 709         CALLE  ...   709.0   

                                   Cruce  \
0    FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                    DE LOS CORRALES AV.   
2                                    NaN   
3               VILLEGAS, CONRADO, GRAL.   
4                SAENZ PE?A, LUIS, PRES.   
..                                   ...   
691                                  MOM   
692                          LACARRA AV.   
693                              TERRADA   
694                                  NaN   
695                                  NaN   

                                 Dirección Normalizada COMUNA  \
0    PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...      8   
1                 PAZ, GRAL. AV. y DE LOS CORRALES AV.      9   
2                                  ENTRE RIOS AV. 2034      1   
3            LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.      8   
4              SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.      1   
..                                                 ...    ...   
691                                  RIESTRA AV. y MOM      7   
692         DELLEPIANE, LUIS, TTE. GRAL. y LACARRA AV.      9   
693                                GAONA AV. y TERRADA     11   
694                                PERON, EVA AV. 4071      9   
695                            PADRE CARLOS MUGICA 709      1   

                                   XY (CABA)         pos x         pos y  \
0      Point (98896.78238426 93532.43437792)  -58.47533969  -34.68757022   
1      Point (95832.05571093 95505.41641999)  -58.50877521  -34.66977709   
2     Point (106684.29090040 99706.57687843)  -58.39040293  -34.63189362   
3      Point (99840.65224780 94269.16534422)  -58.46503904  -34.68092974   
4    Point (106980.32827929 100752.16915795)  -58.38718297  -34.62246630   
..                                       ...           ...           ...   
691   Point (102728.60090138 98186.24929177)  -58.43353773  -34.64561636   
692    Point (99624.29795829 97569.69801131)  -58.46739825  -34.65117757   
693   Point (99116.45492358 101045.23284826)  -58.47293407  -34.61984745   
694    Point (99324.54463985 97676.26932409)  -58.47066794  -34.65021673   
695  Point (107664.16647795 104708.63962087)  -58.37976155  -34.58679619   

      PARTICIPANTES    VICTIMA    A

In [18]:
# Obtener información general del DataFrame
homicidios_hechos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 696 entries, 0 to 695
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   ID                     696 non-null    object        
 1   N_VICTIMAS             696 non-null    int64         
 2   FECHA                  696 non-null    datetime64[ns]
 3   AAAA                   696 non-null    int64         
 4   MM                     696 non-null    int64         
 5   DD                     696 non-null    int64         
 6   HORA                   696 non-null    object        
 7   HH                     696 non-null    object        
 8   LUGAR_DEL_HECHO        696 non-null    object        
 9   TIPO_DE_CALLE          696 non-null    object        
 10  Calle                  695 non-null    object        
 11  Altura                 129 non-null    float64       
 12  Cruce                  525 non-null    object        
 13  Direc

Examen de nulos y duplicados

In [25]:
# Invoca la función 'analizar_valores_sd'
resultados_h_hechos = analizar_valores_sd(homicidios_hechos)
resultados_h_hechos

Columna  Cantidad de SD  Porcentaje de SD
6              HORA               1          0.143678
7                HH               1          0.143678
8   LUGAR_DEL_HECHO               1          0.143678
19          VICTIMA               9          1.293103
20          ACUSADO              23          3.304598

In [28]:
homicidios_hechos.isnull().sum()

ID                         0
N_VICTIMAS                 0
FECHA                      0
AAAA                       0
MM                         0
DD                         0
HORA                       1
HH                         1
LUGAR_DEL_HECHO            1
TIPO_DE_CALLE              0
Calle                      1
Altura                   567
Cruce                    171
Dirección Normalizada      8
COMUNA                     0
XY (CABA)                  0
pos x                      0
pos y                      0
PARTICIPANTES              0
VICTIMA                    9
ACUSADO                   23
dtype: int64

In [27]:
# Reemplazar 'SD' por NaN en todo el DataFrame

homicidios_hechos.replace(['SD','sd'], np.nan, inplace=True)

Se analizan las columnas con datos nulos

In [29]:
homicidios_hechos[["Altura", "Calle", "Dirección Normalizada", "Cruce"]][:5]

Altura             Calle  \
0     NaN  PIEDRA BUENA AV.   
1     NaN    PAZ, GRAL. AV.   
2  2034.0    ENTRE RIOS AV.   
3     NaN    LARRAZABAL AV.   
4     NaN      SAN JUAN AV.   

                               Dirección Normalizada  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.   
2                                ENTRE RIOS AV. 2034   
3          LARRAZABAL AV. y VILLEGAS, CONRADO, GRAL.   
4            SAN JUAN AV. y SAENZ PEÃ‘A, LUIS, PRES.   

                                 Cruce  
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.  
1                  DE LOS CORRALES AV.  
2                                  NaN  
3             VILLEGAS, CONRADO, GRAL.  
4              SAENZ PE?A, LUIS, PRES.

In [30]:
homicidios_hechos[homicidios_hechos["Dirección Normalizada"].isnull()][["Dirección Normalizada", "Cruce","Altura", "Calle"]]

Dirección Normalizada Cruce  Altura                                 Calle
38                    NaN   NaN     NaN                 LUGONES, LEOPOLDO AV.
106                   NaN   NaN     NaN     AUTOPISTA BUENOS AIRES - LA PLATA
119                   NaN   NaN     NaN                                   NaN
180                   NaN   NaN     NaN               AUTOPISTA PERITO MORENO
181                   NaN   NaN     NaN  AUTOPISTA DELLEPIANE LUIS TTE. GRAL.
313                   NaN   NaN     NaN                 LUGONES, LEOPOLDO AV.
546                   NaN   NaN     NaN                 LUGONES, LEOPOLDO AV.
621                   NaN   NaN     NaN     AUTOPISTA BUENOS AIRES - LA PLATA

Tras examinar datos nulos, que representan el 5,1% del dataset; distribuidos en tres columnas **`Altura`**, **`Dirección Normalizada`**, **`Cruce`** y **`Calle`**. 
- Para el caso de **`Calle`** tiene un solo dato nulo.
- Para el caso de  **`Dirección Normalizada`** 8 nulos. 
- Para el caso de **`Cruce`** tiene 171 nulos, siendo el 24,56% del los datos de la columna.
- Para el caso de **`Altura`** tiene 567 nulos que representan el 81,5% de datos de la columna

Analizando los datos de la `Altura` se procede a eliminarla debido a la gran cantidad de faltantes y no existiendo manera de poder rellenar las colummas; ya que altura se refiere a la numeración de la calle donde se produce el siniestro y la mayoria de los casos se producen en cruces o esquinas.
La columna `Cruce` solo va a tener dato cuando el hecho se porduce en un cruce de calles, por lo que se conserva de esta manera.
La columna `Dirección Normalizada` no tiene posibilidad de completarse con las columnas del dataset; pero contiene solo 1,1% de nulos por lo se conserva de esta manera.

In [31]:
# Se elimina la columna "Altura"
homicidios_hechos= homicidios_hechos.drop("Altura", axis=1)
homicidios_hechos.columns

Index(['ID', 'N_VICTIMAS', 'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Cruce',
       'Dirección Normalizada', 'COMUNA', 'XY (CABA)', 'pos x', 'pos y',
       'PARTICIPANTES', 'VICTIMA', 'ACUSADO'],
      dtype='object')

In [32]:
homicidios_hechos.duplicated().sum()

0

Para el caso no se encontraron datos duplicados 

## 4. Transformación de los datos

Se regularizan los tipos de datos de las columnas

Ante la salida de la info del dataset, se observa que la primera columna con tipo de dato que necesita transformación es `HH`, debido a que se encuentra como objeto y deberia ser númerico.
- Por ello se analizan los datos de la columna
- Se transforman a tipo de dato numérico

In [33]:
homicidios_hechos["HH"].unique()

array([ 4.,  1.,  7.,  0.,  5., 18., 19., 15., 11., 22., 16.,  9., 23.,
        6., 10., 17., 12.,  8., 20., 21., 14.,  3.,  2., 13., nan])

El campo que contiene SD, no se modifica debido a que en la columna HORA donde tambien debería existir dato, se encuentra SD. Por lo que no podemos calcular un reemplazo. Otra opción sería calcular la mediana de las horas y reemplazarlas pero podria no ser representativo en este caso. Por lo que se define mantenerlo en SD

In [34]:
# Cambio el dato horas  a tipo de dato numerico y luego a entero 
homicidios_hechos["HH"] = pd.to_numeric(homicidios_hechos ["HH"], errors="coerce")
homicidios_hechos["HH"] = homicidios_hechos["HH"].astype("Int64")

In [35]:
# Filtrar filas con posiciones no válidas
valid_positions = ~(homicidios_hechos['pos x'].str.contains('[^0-9.,-]') | homicidios_hechos['pos y'].str.contains('[^0-9.,-]') | (homicidios_hechos['pos x'] == '.') | (homicidios_hechos['pos y'] == '.'))

# Establecer posiciones no válidas en NaN
homicidios_hechos.loc[~valid_positions, ['pos x', 'pos y']] = np.nan

# Convertir las cadenas a tipo numérico (float)
homicidios_hechos['pos x'] = homicidios_hechos['pos x'].str.replace(',', '.').astype(float)
homicidios_hechos['pos y'] = homicidios_hechos['pos y'].str.replace(',', '.').astype(float)

In [36]:
homicidios_hechos.head(3)

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
0  2016-0001           1 2016-01-01  2016   1   1  04:00:00   4   
1  2016-0002           1 2016-01-02  2016   1   2  01:15:00   1   
2  2016-0003           1 2016-01-03  2016   1   3  07:00:00   7   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE             Calle  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  PIEDRA BUENA AV.   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ    PAZ, GRAL. AV.   
2                         AV ENTRE RIOS 2034       AVENIDA    ENTRE RIOS AV.   

                                 Cruce  \
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                  DE LOS CORRALES AV.   
2                                  NaN   

                               Dirección Normalizada  COMUNA  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...       8   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.       9   
2                                ENTRE RIOS AV. 2034       1   

                                XY (CABA)      pos x      pos y  \
0   Point (98896.78238426 93532.43437792) -58.475340 -34.687570   
1   Point (95832.05571093 95505.41641999) -58.508775 -34.669777   
2  Point (106684.29090040 99706.57687843) -58.390403 -34.631894   

    PARTICIPANTES VICTIMA    ACUSADO  
0       MOTO-AUTO    MOTO       AUTO  
1  AUTO-PASAJEROS    AUTO  PASAJEROS  
2       MOTO-AUTO    MOTO       AUTO

La columna `XY (CABA)` posee coordenadas para poder ubicar en un mapa , las extraemos para poder utilizar

La función extraer_coordenadas se utiliza para extraer estas coordenadas (latitud y longitud) de un texto determinado y luego se almacenan en las columnas 'coordenada_x' (longitud) y 'coordenada_y' (latitud) del DataFrame.

In [37]:
# Función para extraer las coordenadas CABA
# Esta función toma un argumento texto, que es el texto de entrada del cual se intentarán extraer las coordenadas
# Utiliza una expresión regular (re.findall) para buscar todas las coincidencias de números decimales (que tienen un punto como separador decimal) en el texto. Estas coincidencias se almacenan en la lista coordenadas.
# return float(coordenadas[0]), float(coordenadas[1]): Si se encontraron dos coordenadas, se convierten en números de punto flotante (float) y se devuelven como una tupla de dos valores.
# Luego, se aplica esta función a la columna 'XY (CABA)' de df_siniestros utilizando el método .map(). Esto se hace para cada fila de la columna, y los resultados se almacenan en dos nuevas columnas, 'coordenada_x' y 'coordenada_y', utilizando zip(*...).

def extraer_coordenadas(texto):
    # Utilizamos una expresión regular para extraer las coordenadas
    coordenadas = re.findall(r'\d+\.\d+', texto)
    if len(coordenadas) == 2:
        return float(coordenadas[0]), float(coordenadas[1])
    else:
        return None, None

# Aplicar la función a la columna 'XY (CABA)'
homicidios_hechos['coordenada_x'], homicidios_hechos['coordenada_y'] = zip(*homicidios_hechos['XY (CABA)'].map(extraer_coordenadas))

# Filtrar los registros que no tienen coordenadas válidas
homicidios_hechos = homicidios_hechos[(homicidios_hechos['coordenada_x'].notnull()) & (homicidios_hechos['coordenada_y'].notnull())]

In [38]:
homicidios_hechos.head(3)

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
0  2016-0001           1 2016-01-01  2016   1   1  04:00:00   4   
1  2016-0002           1 2016-01-02  2016   1   2  01:15:00   1   
2  2016-0003           1 2016-01-03  2016   1   3  07:00:00   7   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE  ...  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...   
2                         AV ENTRE RIOS 2034       AVENIDA  ...   

                               Dirección Normalizada COMUNA  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...      8   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.      9   
2                                ENTRE RIOS AV. 2034      1   

                                XY (CABA)      pos x      pos y  \
0   Point (98896.78238426 93532.43437792) -58.475340 -34.687570   
1   Point (95832.05571093 95505.41641999) -58.508775 -34.669777   
2  Point (106684.29090040 99706.57687843) -58.390403 -34.631894   

    PARTICIPANTES  VICTIMA    ACUSADO   coordenada_x  coordenada_y  
0       MOTO-AUTO     MOTO       AUTO   98896.782384  93532.434378  
1  AUTO-PASAJEROS     AUTO  PASAJEROS   95832.055711  95505.416420  
2       MOTO-AUTO     MOTO       AUTO  106684.290900  99706.576878  

[3 rows x 22 columns]

In [39]:
#Se observan las columnas resultantes
homicidios_hechos.columns

Index(['ID', 'N_VICTIMAS', 'FECHA', 'AAAA', 'MM', 'DD', 'HORA', 'HH',
       'LUGAR_DEL_HECHO', 'TIPO_DE_CALLE', 'Calle', 'Cruce',
       'Dirección Normalizada', 'COMUNA', 'XY (CABA)', 'pos x', 'pos y',
       'PARTICIPANTES', 'VICTIMA', 'ACUSADO', 'coordenada_x', 'coordenada_y'],
      dtype='object')

En la columna 'Comuna' tenemos una numeracion del 1 al 15. Esta numeración identifica a cada una de las divisiones comunales de la ciudad autónoma de Buenos Aires.

Para agregar valor al dataset, agregaremos la descripción de cada una de las comunas, con los Barrios que la conforman.

Para eso utilizaremos el dataset 'comunas' importado junto al dataset `homicidios`. Este dataset fue descargado del siguiente sitio web: https://buenosaires.gob.ar/comunas

In [40]:
#Se realiza el merge a través de la columna en comun `Comuna` y nos va a quedar anexada la columna `Barrios`

homicidios_hechos=homicidios_hechos.merge(comunas, on="COMUNA", how="left")

#Modifico las mayúsculas por minúsculas
homicidios_hechos=homicidios_hechos.rename(columns={
    "BARRIOS": "Barrios"
})


In [41]:
homicidios_hechos.head(3)

ID  N_VICTIMAS      FECHA  AAAA  MM  DD      HORA  HH  \
0  2016-0001           1 2016-01-01  2016   1   1  04:00:00   4   
1  2016-0002           1 2016-01-02  2016   1   2  01:15:00   1   
2  2016-0003           1 2016-01-03  2016   1   3  07:00:00   7   

                             LUGAR_DEL_HECHO TIPO_DE_CALLE  ... COMUNA  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...      8   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...      9   
2                         AV ENTRE RIOS 2034       AVENIDA  ...      1   

                                XY (CABA)      pos x      pos y  \
0   Point (98896.78238426 93532.43437792) -58.475340 -34.687570   
1   Point (95832.05571093 95505.41641999) -58.508775 -34.669777   
2  Point (106684.29090040 99706.57687843) -58.390403 -34.631894   

    PARTICIPANTES  VICTIMA    ACUSADO   coordenada_x  coordenada_y  \
0       MOTO-AUTO     MOTO       AUTO   98896.782384  93532.434378   
1  AUTO-PASAJEROS     AUTO  PASAJEROS   95832.055711  95505.416420   
2       MOTO-AUTO     MOTO       AUTO  106684.290900  99706.576878   

                                             Barrios  
0     VILLA LUGANO - VILLA RIACHUELO - VILLA SOLDATI  
1            LINIERS - MATADEROS - PARQUE AVELLANEDA  
2  CONSTITUCION - MONTSERRAT - PUERTO MADERO - RE...  

[3 rows x 23 columns]

Las colummas tienen nombres en mayúsculas y también en minúsculas. Se estandarizan a modo de buena práctica

In [42]:
#Cambio la primer letra a mayúscula
homicidios_hechos.columns = [x.capitalize() for x in homicidios_hechos.columns]
# Reemplazo guiones por espacios
homicidios_hechos.columns = homicidios_hechos.columns.str.replace("_", " ")
#Renombra columnas 
homicidios_hechos= homicidios_hechos.rename(columns={"N victimas": "Num víctimas",
                                            "Aaaa": "Año",
                                            "Mm":"Mes",
                                            "Dd": "Día",
                                            "Hora": "Hora completa",
                                            "Hh": "Hora"}) 

homicidios_hechos.columns

Index(['Id', 'Num víctimas', 'Fecha', 'Año', 'Mes', 'Día', 'Hora completa',
       'Hora', 'Lugar del hecho', 'Tipo de calle', 'Calle', 'Cruce',
       'Dirección normalizada', 'Comuna', 'Xy (caba)', 'Pos x', 'Pos y',
       'Participantes', 'Victima', 'Acusado', 'Coordenada x', 'Coordenada y',
       'Barrios'],
      dtype='object')

Al analizar los datos de la columna `Día` se muestra solo el numero del día y no el nombre correspondiente por lo que se crea la columna `Día semana` donde se corresponde cada fecha con un dia de la semana para poder analizar luego como se relacionan los siniestros con los dias de la semana

In [43]:
#Consulto la columna Día
homicidios_hechos.Día

0       1
1       2
2       3
3      10
4      21
       ..
677    13
678    20
679    30
680    15
681    18
Name: Día, Length: 682, dtype: int64

In [44]:
#Creo una columna nueva `Día semana` que contenga el nombre del día de la semana
homicidios_hechos['Día semana'] = homicidios_hechos['Fecha'].dt.strftime('%A')

#Creo un diccionario para modificar a español los nombres de los dás de la semana y lo aplico a la columna nueva
dic={  'Friday':'Viernes',
       'Saturday': 'Sabado',
       'Sunday': 'Domingo',  
       'Thursday': 'Jueves',
        'Monday': 'Lunes',
        'Wednesday': 'Miercoles',
       'Tuesday': 'Martes'}
homicidios_hechos['Día semana'] =homicidios_hechos['Día semana'].replace(dic)

In [45]:
homicidios_hechos.head(3)

Id  Num víctimas      Fecha   Año  Mes  Día Hora completa  Hora  \
0  2016-0001             1 2016-01-01  2016    1    1      04:00:00     4   
1  2016-0002             1 2016-01-02  2016    1    2      01:15:00     1   
2  2016-0003             1 2016-01-03  2016    1    3      07:00:00     7   

                             Lugar del hecho Tipo de calle  ...  \
0  AV PIEDRA BUENA Y AV FERNANDEZ DE LA CRUZ       AVENIDA  ...   
1          AV GRAL PAZ  Y AV DE LOS CORRALES      GRAL PAZ  ...   
2                         AV ENTRE RIOS 2034       AVENIDA  ...   

                                Xy (caba)      Pos x      Pos y  \
0   Point (98896.78238426 93532.43437792) -58.475340 -34.687570   
1   Point (95832.05571093 95505.41641999) -58.508775 -34.669777   
2  Point (106684.29090040 99706.57687843) -58.390403 -34.631894   

    Participantes Victima    Acusado   Coordenada x  Coordenada y  \
0       MOTO-AUTO    MOTO       AUTO   98896.782384  93532.434378   
1  AUTO-PASAJEROS    AUTO  PASAJEROS   95832.055711  95505.416420   
2       MOTO-AUTO    MOTO       AUTO  106684.290900  99706.576878   

                                             Barrios Día semana  
0     VILLA LUGANO - VILLA RIACHUELO - VILLA SOLDATI    Viernes  
1            LINIERS - MATADEROS - PARQUE AVELLANEDA     Sabado  
2  CONSTITUCION - MONTSERRAT - PUERTO MADERO - RE...    Domingo  

[3 rows x 24 columns]

La colmuna `Comuna` se modifica agregando el termino Comuna antes del número, a fin de lograr una variable categórica que me simplifique el análisis

In [46]:
homicidios_hechos["Comuna"].unique()

array([ 8,  9,  1, 11, 15,  4,  7, 12,  3, 13, 14, 10,  6,  2,  5],
      dtype=int64)

In [47]:
#Agrego la palabra Comuna delante del dato numérico
#se aplica la función lambda a cada fila del dataframe 
homicidios_hechos["Comuna"] = homicidios_hechos.apply(lambda x: "Comuna "+str(x["Comuna"]), axis=1)


In [48]:
homicidios_hechos["Comuna"].unique()

array(['Comuna 8', 'Comuna 9', 'Comuna 1', 'Comuna 11', 'Comuna 15',
       'Comuna 4', 'Comuna 7', 'Comuna 12', 'Comuna 3', 'Comuna 13',
       'Comuna 14', 'Comuna 10', 'Comuna 6', 'Comuna 2', 'Comuna 5'],
      dtype=object)

Se realiza un resumen descriptivo de los datos en `homicidios-hechos`

In [49]:
dfSummary(homicidios_hechos)

## Tratamiento de los datos del dataset `homicidios- víctimas`

In [50]:
homicidios_victimas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype         
---  ------               --------------  -----         
 0   ID_hecho             717 non-null    object        
 1   FECHA                717 non-null    datetime64[ns]
 2   AAAA                 717 non-null    int64         
 3   MM                   717 non-null    int64         
 4   DD                   717 non-null    int64         
 5   ROL                  717 non-null    object        
 6   VICTIMA              717 non-null    object        
 7   SEXO                 717 non-null    object        
 8   EDAD                 717 non-null    object        
 9   FECHA_FALLECIMIENTO  717 non-null    object        
dtypes: datetime64[ns](1), int64(3), object(6)
memory usage: 56.1+ KB


### Transformación de los datos

Conversión del tipo de dato

In [51]:
#Cambio la columna a tipo datetime
homicidios_victimas["FECHA_FALLECIMIENTO"] = pd.to_datetime(homicidios_victimas["FECHA_FALLECIMIENTO"], format='%Y-%m-%d', errors='coerce')

In [54]:
#Una vez que se paso el tipo de dato a datetime que es una fecha y hora completa se utiliza este codigo para que solo se quede en formato fecha sin hora
homicidios_victimas["FECHA_FALLECIMIENTO"] = homicidios_victimas["FECHA_FALLECIMIENTO"].dt.date

#Luego se reemplazan las fechas en cero con espacios vacios a fin de su manipulación
homicidios_victimas["FECHA_FALLECIMIENTO"] = homicidios_victimas ["FECHA_FALLECIMIENTO"].replace(pd.NaT,"")

In [55]:
#Cambio la columna edad a numerico y luego a tipo entero
homicidios_victimas ["EDAD"] = pd.to_numeric(homicidios_victimas["EDAD"], errors="coerce")
homicidios_victimas ["EDAD"] = homicidios_victimas["EDAD"].astype("Int64")

In [56]:
#Utilizo Numpy para reemplazar por NaN los sin datos o vacios y luego paso a float para que cuando quiera aplicar estadisticas no tenga errores debido a esos datos
homicidios_victimas["EDAD"] = homicidios_victimas["EDAD"].replace([" ","SD"], np.nan)

In [57]:
homicidios_victimas["EDAD"] = homicidios_victimas["EDAD"].fillna(0.0)

In [58]:
#Controlo los datos de la columna
homicidios_victimas ["EDAD"].unique()

<IntegerArray>
[19, 70, 30, 18, 29, 22, 16, 59, 65, 34, 41, 50, 38, 21, 52, 36, 20, 54,  0,
 56, 24, 78, 79, 26, 57, 37, 58, 23, 60, 42, 53, 51, 40, 87, 76, 75, 35, 80,
 43, 45, 67, 27, 55, 49, 81, 25, 33, 46, 83, 39, 28,  7, 48,  4, 82, 32, 17,
 47, 61, 10, 95, 73, 84, 66, 85,  1, 15, 13, 77, 44, 31, 62, 74, 71, 11, 86,
 69, 72, 12, 63, 92, 68, 91, 64,  5, 88]
Length: 86, dtype: Int64

In [59]:
homicidios_victimas.head(3)

ID_hecho      FECHA  AAAA  MM  DD        ROL VICTIMA       SEXO  EDAD  \
0  2016-0001 2016-01-01  2016   1   1  CONDUCTOR    MOTO  MASCULINO    19   
1  2016-0002 2016-01-02  2016   1   2  CONDUCTOR    AUTO  MASCULINO    70   
2  2016-0003 2016-01-03  2016   1   3  CONDUCTOR    MOTO  MASCULINO    30   

  FECHA_FALLECIMIENTO  
0          2016-01-01  
1          2016-01-02  
2          2016-01-03

In [60]:
homicidios_victimas.isnull().sum()

ID_hecho               0
FECHA                  0
AAAA                   0
MM                     0
DD                     0
ROL                    0
VICTIMA                0
SEXO                   0
EDAD                   0
FECHA_FALLECIMIENTO    0
dtype: int64

No se encuentran datos nulos, ni campos vacios

Se crea la columna `Rango etario` basada en la columna `Edad`, para mejorar el análisis de los datos 

In [61]:

# Se utiliza la función `pd.cut()`, que permite agrupar valores numéricos en intervalos o categorías


# Definir los límites de los rangos etarios y las etiquetas
bins = [0, 20, 40, 60, 80, 100]
labels = ['Menos de 20', ' Entre 21- 40', 'Entre 41-60', 'Entre 61-80', 'Más de 80']

# Utilizar pd.cut() para crear la columna de rango etario
homicidios_victimas['Rango_etario'] = pd.cut(homicidios_victimas['EDAD'], bins=bins, labels=labels, right=False)

homicidios_victimas.head(3)


ID_hecho      FECHA  AAAA  MM  DD        ROL VICTIMA       SEXO  EDAD  \
0  2016-0001 2016-01-01  2016   1   1  CONDUCTOR    MOTO  MASCULINO    19   
1  2016-0002 2016-01-02  2016   1   2  CONDUCTOR    AUTO  MASCULINO    70   
2  2016-0003 2016-01-03  2016   1   3  CONDUCTOR    MOTO  MASCULINO    30   

  FECHA_FALLECIMIENTO   Rango_etario  
0          2016-01-01    Menos de 20  
1          2016-01-02    Entre 61-80  
2          2016-01-03   Entre 21- 40

A continuación se estandarizan las mayúsculas y minúsculas del dataset

In [62]:
# Se coloca la primera en mayúscula
homicidios_victimas.columns = [x.capitalize() for x in homicidios_victimas.columns]
# Se reemplazan los guiones por espacios
homicidios_victimas.columns = homicidios_victimas.columns.str.replace('_', ' ')
# Se renombran algunas columnas
homicidios_victimas = homicidios_victimas.rename(columns={'Id hecho': 'Id',
                                                      'Aaaa':'Año',
                                                      'Mm':'Mes',
                                                      'Dd':'Día',
                                                      'Victima':'Víctima'})
homicidios_victimas.columns

Index(['Id', 'Fecha', 'Año', 'Mes', 'Día', 'Rol', 'Víctima', 'Sexo', 'Edad',
       'Fecha fallecimiento', 'Rango etario'],
      dtype='object')

A partir de los datos, se analiza eliminar columnas que se repiten en ambos dataset para realizar luego la unión y trabajar con un conjunto de datos.
Se proceden a eliminar del dataset `homicidios_victimas` las columnas `Fecha`, `Año`, `Mes`, `Día` y `Victima` que contienen la misma información que se encuentra en `homicidios_hechos`. 

In [63]:
#Se busca un registro para comparar con el mismo registro en el otro dataset
homicidios_hechos[homicidios_hechos["Id"]=="2019-0012"]

Id  Num víctimas      Fecha   Año  Mes  Día Hora completa  Hora  \
418  2019-0012             1 2019-02-17  2019    2   17      03:16:00     3   

                        Lugar del hecho Tipo de calle  ...  \
418  CASTAÑARES AV. Y GORDILLO, TIMOTEO       AVENIDA  ...   

                                 Xy (caba)      Pos x      Pos y  \
418  Point (98072.98959434 94742.80804806) -58.484327 -34.676658   

    Participantes Victima  Acusado  Coordenada x  Coordenada y  \
418     MOTO-AUTO    MOTO     AUTO  98072.989594  94742.808048   

                                            Barrios Día semana  
418  VILLA LUGANO - VILLA RIACHUELO - VILLA SOLDATI    Domingo  

[1 rows x 24 columns]

In [64]:
homicidios_victimas[homicidios_victimas["Id"]=="2019-0012"]

Id      Fecha   Año  Mes  Día        Rol Víctima       Sexo  Edad  \
447  2019-0012 2019-02-17  2019    2   17  CONDUCTOR    MOTO  MASCULINO    31   

    Fecha fallecimiento   Rango etario  
447          2019-02-20   Entre 21- 40

Se realiza un resumen descriptivo de los datos en `homicidios-victimas`

In [65]:
dfSummary(homicidios_victimas)

In [66]:
# Se eliminan las columnas repetidas
homicidios_victimas = homicidios_victimas.drop(['Fecha', 'Año', 'Mes', 'Día', 'Víctima'], axis=1)
homicidios_victimas.columns

Index(['Id', 'Rol', 'Sexo', 'Edad', 'Fecha fallecimiento', 'Rango etario'], dtype='object')

## Unificación de los dataset

Por medio de la función merge se unifican los dataset transformados anteriormente

In [67]:
siniestros= homicidios_victimas.merge(homicidios_hechos, on="Id", how="left")
siniestros.columns

Index(['Id', 'Rol', 'Sexo', 'Edad', 'Fecha fallecimiento', 'Rango etario',
       'Num víctimas', 'Fecha', 'Año', 'Mes', 'Día', 'Hora completa', 'Hora',
       'Lugar del hecho', 'Tipo de calle', 'Calle', 'Cruce',
       'Dirección normalizada', 'Comuna', 'Xy (caba)', 'Pos x', 'Pos y',
       'Participantes', 'Victima', 'Acusado', 'Coordenada x', 'Coordenada y',
       'Barrios', 'Día semana'],
      dtype='object')

In [68]:
siniestros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   Id                     717 non-null    object        
 1   Rol                    717 non-null    object        
 2   Sexo                   717 non-null    object        
 3   Edad                   717 non-null    Int64         
 4   Fecha fallecimiento    717 non-null    object        
 5   Rango etario           717 non-null    category      
 6   Num víctimas           702 non-null    float64       
 7   Fecha                  702 non-null    datetime64[ns]
 8   Año                    702 non-null    float64       
 9   Mes                    702 non-null    float64       
 10  Día                    702 non-null    float64       
 11  Hora completa          701 non-null    object        
 12  Hora                   701 non-null    Int64         
 13  Lugar

Al unificar los dataset se encontraron datos cambiados a tipo float que son necesarios como enteros, por lo que se transforman

In [69]:
siniestros["Num víctimas"].unique()

array([ 1.,  2., nan,  3.])

In [70]:
siniestros ["Num víctimas"] = siniestros ["Num víctimas"].fillna(0.0)
siniestros ["Num víctimas"] = siniestros ["Num víctimas"].astype ("Int64")

In [71]:
siniestros["Num víctimas"].unique()

<IntegerArray>
[1, 2, 0, 3]
Length: 4, dtype: Int64

In [72]:
siniestros["Año"].unique()

array([2016.,   nan, 2017., 2018., 2019., 2020., 2021.])

In [73]:
siniestros ["Año"]= siniestros ["Año"].astype ("Int64")
siniestros["Año"].unique()

<IntegerArray>
[2016, <NA>, 2017, 2018, 2019, 2020, 2021]
Length: 7, dtype: Int64

In [74]:
siniestros ["Mes"]= siniestros ["Mes"].astype ("Int64")
siniestros["Mes"].unique()

<IntegerArray>
[1, 2, 3, 4, <NA>, 5, 6, 7, 8, 9, 10, 11, 12]
Length: 13, dtype: Int64

In [75]:
siniestros ["Día"]= siniestros ["Día"].astype ("Int64")
siniestros["Día"].unique()

<IntegerArray>
[   1,    2,    3,   10,   21,   24,   29,    8,   14,   15,   17,   28,    4,
   12,   13,   19,   23,   30,   31,   11, <NA>,   20,   22,   25,   26,   16,
   18,   27,    7,    9,    5,    6]
Length: 32, dtype: Int64

In [76]:
siniestros.head(3)

Id        Rol       Sexo  Edad Fecha fallecimiento   Rango etario  \
0  2016-0001  CONDUCTOR  MASCULINO    19          2016-01-01    Menos de 20   
1  2016-0002  CONDUCTOR  MASCULINO    70          2016-01-02    Entre 61-80   
2  2016-0003  CONDUCTOR  MASCULINO    30          2016-01-03   Entre 21- 40   

   Num víctimas      Fecha   Año  Mes  ...  \
0             1 2016-01-01  2016    1  ...   
1             1 2016-01-02  2016    1  ...   
2             1 2016-01-03  2016    1  ...   

                                Xy (caba)      Pos x      Pos y  \
0   Point (98896.78238426 93532.43437792) -58.475340 -34.687570   
1   Point (95832.05571093 95505.41641999) -58.508775 -34.669777   
2  Point (106684.29090040 99706.57687843) -58.390403 -34.631894   

    Participantes Victima    Acusado   Coordenada x  Coordenada y  \
0       MOTO-AUTO    MOTO       AUTO   98896.782384  93532.434378   
1  AUTO-PASAJEROS    AUTO  PASAJEROS   95832.055711  95505.416420   
2       MOTO-AUTO    MOTO       AUTO  106684.290900  99706.576878   

                                             Barrios Día semana  
0     VILLA LUGANO - VILLA RIACHUELO - VILLA SOLDATI    Viernes  
1            LINIERS - MATADEROS - PARQUE AVELLANEDA     Sabado  
2  CONSTITUCION - MONTSERRAT - PUERTO MADERO - RE...    Domingo  

[3 rows x 29 columns]

Se realiza un resumen descriptivo de los datos de `siniestros` 

In [77]:
siniestros.describe()

Edad  Num víctimas                          Fecha          Año  \
count      717.0         717.0                            702        702.0   
mean   39.050209      1.037657  2018-09-15 17:48:43.076922880  2018.192308   
min          0.0           0.0            2016-01-01 00:00:00       2016.0   
25%         24.0           1.0            2017-04-05 18:00:00       2017.0   
50%         35.0           1.0            2018-07-14 12:00:00       2018.0   
75%         55.0           1.0            2019-12-20 06:00:00       2019.0   
max         95.0           3.0            2021-12-30 00:00:00       2021.0   
std    22.010669      0.294226                            NaN     1.669154   

            Mes       Día       Hora       Pos x       Pos y   Coordenada x  \
count     702.0     702.0      701.0  702.000000  702.000000     702.000000   
mean   6.693732  15.92735  11.573466  -58.441710  -34.619609  101980.113004   
min         1.0       1.0        0.0  -58.529942  -34.705250   93889.867899   
25%        3.25       9.0        6.0  -58.476995  -34.643801   98744.378735   
50%         7.0      16.0       11.0  -58.444513  -34.622835  101721.590022   
75%        10.0      23.0       17.0  -58.401892  -34.596969  105630.884244   
max        12.0      31.0       23.0  -58.356082  -34.534654  109831.098614   
std    3.584551  8.657478   6.667562    0.046383    0.035291    4253.717694   

        Coordenada y  
count     702.000000  
mean   101070.596233  
min     91571.233073  
25%     98387.965943  
50%    100711.696729  
75%    103582.742374  
max    110496.053085  
std      3914.938863

In [78]:
dfSummary(siniestros)

Antes de realizar en EDA propiamiente dicho se ordenan las columnas

In [79]:
#Creo una lista con el orden 
nuevo_orden=["Id", "Fecha", "Año", "Mes", "Día","Día semana", "Hora completa", "Hora", "Num víctimas", "Participantes", "Rol", "Acusado", "Victima", "Sexo", "Edad", "Rango etario", "Fecha fallecimiento", "Lugar del hecho", "Tipo de calle", "Calle", "Cruce", "Dirección normalizada", "Comuna", "Barrios", "Xy (caba)", "Coordenada x", "Coordenada y", "Pos x", "Pos y"]

#Reorganizo el dataframe untilizando la lista y asignandola nuevamente aldataframe siniestros
siniestros_limpio = siniestros[nuevo_orden]
siniestros_limpio.columns



Index(['Id', 'Fecha', 'Año', 'Mes', 'Día', 'Día semana', 'Hora completa',
       'Hora', 'Num víctimas', 'Participantes', 'Rol', 'Acusado', 'Victima',
       'Sexo', 'Edad', 'Rango etario', 'Fecha fallecimiento',
       'Lugar del hecho', 'Tipo de calle', 'Calle', 'Cruce',
       'Dirección normalizada', 'Comuna', 'Barrios', 'Xy (caba)',
       'Coordenada x', 'Coordenada y', 'Pos x', 'Pos y'],
      dtype='object')

In [80]:
siniestros_limpio.head(3)

Id      Fecha   Año  Mes  Día Día semana Hora completa  Hora  \
0  2016-0001 2016-01-01  2016    1    1    Viernes      04:00:00     4   
1  2016-0002 2016-01-02  2016    1    2     Sabado      01:15:00     1   
2  2016-0003 2016-01-03  2016    1    3    Domingo      07:00:00     7   

   Num víctimas   Participantes  ...             Calle  \
0             1       MOTO-AUTO  ...  PIEDRA BUENA AV.   
1             1  AUTO-PASAJEROS  ...    PAZ, GRAL. AV.   
2             1       MOTO-AUTO  ...    ENTRE RIOS AV.   

                                 Cruce  \
0  FERNANDEZ DE LA CRUZ, F., GRAL. AV.   
1                  DE LOS CORRALES AV.   
2                                  NaN   

                               Dirección normalizada    Comuna  \
0  PIEDRA BUENA AV. y FERNANDEZ DE LA CRUZ, F., G...  Comuna 8   
1               PAZ, GRAL. AV. y DE LOS CORRALES AV.  Comuna 9   
2                                ENTRE RIOS AV. 2034  Comuna 1   

                                             Barrios  \
0     VILLA LUGANO - VILLA RIACHUELO - VILLA SOLDATI   
1            LINIERS - MATADEROS - PARQUE AVELLANEDA   
2  CONSTITUCION - MONTSERRAT - PUERTO MADERO - RE...   

                                Xy (caba)   Coordenada x  Coordenada y  \
0   Point (98896.78238426 93532.43437792)   98896.782384  93532.434378   
1   Point (95832.05571093 95505.41641999)   95832.055711  95505.416420   
2  Point (106684.29090040 99706.57687843)  106684.290900  99706.576878   

       Pos x      Pos y  
0 -58.475340 -34.687570  
1 -58.508775 -34.669777  
2 -58.390403 -34.631894  

[3 rows x 29 columns]

In [81]:
siniestros_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   Id                     717 non-null    object        
 1   Fecha                  702 non-null    datetime64[ns]
 2   Año                    702 non-null    Int64         
 3   Mes                    702 non-null    Int64         
 4   Día                    702 non-null    Int64         
 5   Día semana             702 non-null    object        
 6   Hora completa          701 non-null    object        
 7   Hora                   701 non-null    Int64         
 8   Num víctimas           717 non-null    Int64         
 9   Participantes          702 non-null    object        
 10  Rol                    717 non-null    object        
 11  Acusado                683 non-null    object        
 12  Victima                695 non-null    object        
 13  Sexo 

In [82]:
siniestros_limpio["Fecha"]=siniestros_limpio["Fecha"].dt.date

In [83]:
siniestros_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype   
---  ------                 --------------  -----   
 0   Id                     717 non-null    object  
 1   Fecha                  702 non-null    object  
 2   Año                    702 non-null    Int64   
 3   Mes                    702 non-null    Int64   
 4   Día                    702 non-null    Int64   
 5   Día semana             702 non-null    object  
 6   Hora completa          701 non-null    object  
 7   Hora                   701 non-null    Int64   
 8   Num víctimas           717 non-null    Int64   
 9   Participantes          702 non-null    object  
 10  Rol                    717 non-null    object  
 11  Acusado                683 non-null    object  
 12  Victima                695 non-null    object  
 13  Sexo                   717 non-null    object  
 14  Edad                   717 non-null    Int

In [84]:
dfSummary(siniestros_limpio, is_collapsible=True)

## Exportar CSV Limpio
Se guarda el archivo como csv para optimizar su manipulación

In [67]:
siniestros_limpio.to_csv("data/siniestos_limpio.csv", index=False)

In [86]:
siniestros_limpio.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 717 entries, 0 to 716
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype   
---  ------                 --------------  -----   
 0   Id                     717 non-null    object  
 1   Fecha                  702 non-null    object  
 2   Año                    702 non-null    Int64   
 3   Mes                    702 non-null    Int64   
 4   Día                    702 non-null    Int64   
 5   Día semana             702 non-null    object  
 6   Hora completa          701 non-null    object  
 7   Hora                   701 non-null    Int64   
 8   Num víctimas           717 non-null    Int64   
 9   Participantes          702 non-null    object  
 10  Rol                    717 non-null    object  
 11  Acusado                683 non-null    object  
 12  Victima                695 non-null    object  
 13  Sexo                   717 non-null    object  
 14  Edad                   717 non-null    Int

## Conectarse desde Clever Cloud a SQL

In [85]:
# Reemplaza 'nombre_de_usuario', 'contraseña', 'nombre_de_base_de_datos' con tus propios valores
nombre_de_usuario = 'u4f4otqetsyqgwbk'
contraseña = 'ni92t8kuAE5uK37JkdTM'
nombre_de_base_de_datos = 'bjxjaprxrl2bg5tyhzy6'
host = 'bjxjaprxrl2bg5tyhzy6-mysql.services.clever-cloud.com'

# Crear la conexión a la base de datos utilizando mysql-connector-python
engine = sqlalchemy.create_engine(f'mysql+mysqlconnector://{nombre_de_usuario}:{contraseña}@{host}/{nombre_de_base_de_datos}')

# Imprimir mensaje si la conexión es exitosa
try:
    connection = engine.connect()
    print("Conexión con la base de datos MySQL exitosa.")
except Exception as e:
    print(f"Error al conectar con la base de datos MySQL: {e}")

# Exportar el DataFrame a la tabla 'Homicidios'
siniestros_limpio.to_sql('siniestros_limpio', engine, if_exists='replace',index=False)

Conexión con la base de datos MySQL exitosa.


717